#ifndef _ROBOT_HPP_
#define _ROBOT_HPP_

/**
 * Motors
 */
#define FRONT_LEFT_WHEEL_PORT 20
#define BACK_LEFT_WHEEL_PORT 19
#define FRONT_RIGHT_WHEEL_PORT 11
#define BACK_RIGHT_WHEEL_PORT 12

#define LAUNCHER_PORT 1
#define TOP_INTAKE_PORT 2
#define BOTTOM_INTAKE_PORT 4
#define EXPANSION_PORT 5

#endif //_ROBOT_HPP_